spring:
  application:
    name: notification
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timeout: 30000

server:
  port: 8084

rabbitmq:
  queue:
    name: order.queue
  exchange:
    name: order.exchange
  routing:
    key: order.tracking