
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: stala
    password: stala
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083