spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: stala
    password: stala
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8081