spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: userdb
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timeout: 30000
management:
      endpoints:
        web:
          exposure:
            include: "*"
      tracing:
        sampling:
          probability: 1.0

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

    register-with-eureka: true
    fetch-registry: true
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7